### ISSUE TITLE
Any other installation way?

### ISSUE THREAD

**Issue by francesco1119** [Dropbox-PHP/dropbox-php#25]
Hello,

I have my Drupal installation on a shared server and I cannot use the "pear" command. Is there any other way out for installing your module?

Thank you

**Comment by lazyguru** [comment]
Actually, the preferred install method is to use composer.  This has been updated on the site but not in the README file yet:  http://www.dropbox-php.com/

**Comment by lazyguru** [comment]
Updated README for installation instructions using composer
