### ISSUE TITLE
Support Upload a file from url in the library

### ISSUE THREAD

**Issue by khurshid-alam** [Dropbox-PHP/dropbox-php#27]
Dropbox now support upload any file from a direct url. 

https://www.dropbox.com/developers/core/docs#save-url

The API endpoint is : https://api.dropbox.com/1/save_url/auto/<path> which takes `path` and `url` as POST parameter.

It would nice if we have this feature in this library.

Thanks

**Comment by lazyguru** [comment]
Please fill free to create a PR and submit the change. This library is no longer actively supported as Dropbox has their own official library. I will however merge any PRs that have passing unit tests
