### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by ghost** [Dropbox-PHP/dropbox-php#29]
I've been using this library for years. Sudden error (500 Internal Server Error) trying to createfolder() (it's the only one I use). Does this library still work?

**Comment by lazyguru** [comment]
You could try running the unit tests. If something changed on Dropbox's end to break the library, it would be pretty recent as I think. The Travis builds passed pretty recently. Additionally, Dropbox has an official PHP package that you could switch too.

**Comment by lazyguru** [comment]
If you decide to debug the issue and provide a fix, I'll accept a PR
