### ISSUE TITLE
Wrong/case insensitive file name index, in delta call

### ISSUE THREAD

**Issue by itsazzad** [Dropbox-PHP/dropbox-php#30]
Dropbox delta call is giving case insensitive file list in the index.
Actual name is: `'/CaSeSeNSiTivE/CaSeSeNSiTivE.docx'`
But showing as: `'/casesensitive/casesensitive.docx'`
```

    0 => 
    array (
      0 => '/casesensitive/casesensitive.docx',
      1 => 
      array (
        'rev' => '---',
        'thumb_exists' => false,
        'path' => '/CaSeSeNSiTivE/CaSeSeNSiTivE.docx',
        'is_dir' => false,
        'client_mtime' => 'Mon, 17 Aug 2015 12:54:14 +0000',
        'icon' => 'page_white_word',
        'bytes' => 4310,
        'modified' => 'Mon, 17 Aug 2015 14:37:52 +0000',
        'size' => '4.2 KB',
        'root' => 'app_folder',
        'mime_type' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'revision' => 618,
      ),
    ),
    1 => 
    array (
      0 => '/casesensitive/case sensitive.docx',
      1 => NULL,
    ),
```

![screenshot 2015-08-17 18 59 12](https://cloud.githubusercontent.com/assets/54909/9307457/7f01641a-4520-11e5-9105-98fff950777d.png)
![screenshot 2015-08-17 20 41 18](https://cloud.githubusercontent.com/assets/54909/9307456/7f012c3e-4520-11e5-9834-b4bbc1cf5b9c.png)
![screenshot 2015-08-17 20 41 30](https://cloud.githubusercontent.com/assets/54909/9307458/7f065aba-4520-11e5-86ae-5f885501fbec.png)

**Comment by lazyguru** [comment]
If I am reading this correctly, this should be reported to Dropbox, not here.  This library has no control over how Dropbox returns filenames (or how it's underlying filesystem treats them as case-sensitive or case-insensitive)

**Comment by itsazzad** [comment]
@lazyguru sorry, my bad.
I thought its the sdk page.
Thanks
