### ISSUE TITLE
DropboxException Request Token with message 'Error: (400) v1 retired

### ISSUE THREAD

**Issue by clintre** [Dropbox-PHP/dropbox-php#32]
Dropbox has retired the v1 API. Any plans to update this with the new version?

**Comment by lazyguru** [comment]
Sorry, but this package has been deprecated for a few years now (after Dropbox released their official PHP SDK). I’ll still process PRs, but my suggestion would be for you to use the official SDK instead.

**Comment by dustinbolton** [comment]
@lazyguru Unfortunately Dropbox no longer has an official PHP SDK anymore. Crazy, I know! :( Their latest official one before they abandoned it uses the v1 API so it's dead too.

**Comment by lazyguru** [comment]
Oh, I wasn't aware of that.  I suppose I can remove the "deprecated" tag pointing people at the official SDK then.  As for updating this one, I'm not sure when I would personally have time to get to it.  As I said above I'll process PRs if anyone wants to help out.  I would ask that you submit unit tests with anything you do as we have pretty decent test coverage currently thanks to a community member.

**Comment by lazyguru** [comment]
Putting this here for reference: https://www.dropbox.com/developers/reference/migration-guide
